### ISSUE TITLE
How does it handle name clashes?

### ISSUE THREAD

**Issue by BeastyBlacksmith** [TsurHerman/Fezzik#5]
I am compiling a system image and it seems to get confused because both `Plots` and `PGFPlots` export `Plot` and then I get a bunch of `UndefVarError`s.

Building the Image nevertheless got me 
```
ErrorException("error compiling inqmathtex: could not load library "libGR.so"
dlopen(libGR.so.dylib, 1): image not found")
```
Which seems related to `GR`.

**Comment by TsurHerman** [comment]
There is no attempt to handle name clashes.
I suggest you start over using the revert option or by reinstalling Julia.
Then trace your work with import instead of ”using” , and use fully qualified name e.g
GR.plot etc.
Only then try brute building a new sysimg. The relevant packages will be imported on startup and all name clashes will be resolved on runtime. 

...on a second thought that might not work since I think the problem is do to some non-intuitive machinery on the general Plots package with its @requires mechanism.

Another thing to try is blacklisting Plots or AbstractPlotting

I personally use PyPlot and it is sufficient for my use cases. 

Let me know if you have more insights on this issue.

**Comment by mdpetters** [comment]
Copying the .so files from the GR package deps directory to the sysimg directory of the julia install worked for me to resolve the ```  could not load library "libGR.so"``` issue.

```
cp $JULIA_PKGDIR/packages/GR/oiZD3/deps/gr/lib/*.so PATH-TO-JULIA-INSTALL/lib/julia/
```

**Comment by TsurHerman** [comment]
@BeastyBlacksmith does the proposed solution solves your issue?

**Comment by BeastyBlacksmith** [comment]
I can't really tell I tried again today and got a segmentation fault
```
┌ Info: UndefVarError(Symbol("##24#30"))
│   LINE = 914
└ @ Main.##anon_module#363 /Users/christ/.julia/packages/Fezzik/xiUBu/precomp.jl:917
compiling line 949
signal (11): Segmentation fault: 11
in expression starting at /Users/christ/.julia/packages/Fezzik/xiUBu/precomp.jl:954
_platform_strcmp at /usr/lib/system/libsystem_platform.dylib (unknown line)
Allocations: 149280558 (Pool: 149248952; Big: 31606); GC: 326
```

**Comment by TsurHerman** [comment]
Yes I get that error too on my mac from time to time... Try a different order of building a sysimg.
First build is just to include updated packages with some additional common functionality like interacting with Atom or the packages manager, some simple arithmetic etc.

Second build after you include GR with a single plot.

And then the most complete routine... It is not ideal but so far I didn't have time to drill down to the root cause.
I have some hope this set fault will go away with future versions of Julia.

**Comment by TsurHerman** [comment]
Better handling of name clashes in the new version(0.4.0)
